### PR TITLE
Pt

### PR DESCRIPTION
**Pull request by kristenmscott**
pt/md folder contains md resources used

### CODE REVIEW

**Review by bpotard — CHANGES_REQUESTED** [review]
Please remove all build/temporary files; you seem to have dozens of them in:
 - idlak-misc/cart_lts
 - idlak-misc/script_gen
 - src/html

**Comment by kristenmscott** [comment]
> Please remove all build/temporary files; you seem to have dozens of them in:
> 
>     * idlak-misc/cart_lts
> 
>     * idlak-misc/script_gen
> 
>     * src/html

deleted tmp dirs from these locations

**Comment by dabraude** [comment]
seems to be changes to languages other than PT is this deliberate?

**Comment by kristenmscott** [comment]
no changes to other languages than pt are not deliberate

**Pull request merged**
